name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: move-safe-webapp/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: move-safe-webapp

    - name: Ensure output is set correctly
      run: |
        if ! grep -q "output: 'export'" move-safe-webapp/next.config.js; then
          echo "module.exports = { output: 'export', ...require('./next.config.js') };" > move-safe-webapp/next.config.tmp.js
          mv move-safe-webapp/next.config.tmp.js move-safe-webapp/next.config.js
        fi

    - name: Build project
      run: npm run build
      working-directory: move-safe-webapp

    - name: Upload to GitHub Pages
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: move-safe-webapp/out
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
