name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: move-safe-webapp/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: move-safe-webapp

    - name: Ensure Next.js config is set correctly
      run: |
        echo "export default { output: 'export' };" > move-safe-webapp/next.config.mjs

    - name: Build project
      run: npm run build
      working-directory: move-safe-webapp

    - name: Upload to GitHub Pages
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: move-safe-webapp/out/
        if-no-files-found: error

    - name: List contents of artifact directory
      run: ls -R move-safe-webapp/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: ./out

    - name: List available artifacts
      run: ls -R ./out || echo "No artifact found!"
      
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
